#
# logging config file location
#
logging:
  config: classpath:config/log/logback-spring.xml
  path: target/logs
  level:
    default: INFO



#
#  datasource
#
#study:
#  datasource:
#    master:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://192.168.80.36:3306/test?characterEncoding=UTF-8&amp;autoReconnect=true&amp;rewriteBatchedStatements=true&allowMultiQueries=true
#      username: lekuda
#      password: 123456
#      max-active: 10
#      min-idle: 0
study:
  datasource:
    master:
      type: com.alibaba.druid.pool.xa.DruidXADataSource
      name: test
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 12345


    slave:
      type: com.alibaba.druid.pool.xa.DruidXADataSource
      name: test2
      url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 12345


#  #jta相关参数配置
spring:
  jta:
    #false:禁用JTA自动配置功能。可以使得本地事务也可以执行。true：彻底使用JTA环境，自动配置JMS，DataSource和JPA　beans将被升级以支持XA事务。
    enabled: true
    #日志地址，默认根目录下transaction-logs
    #log-dir: classpath:tx-logs
    #每个Atomikos的唯一ID,默认为ip地址
    #transaction-manager-id: txManager
  #autoconfigure:
    #exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
