#
# logging config file location
#
logging:
  config: classpath:config/log/logback-spring.xml
  path: target/logs
  level:
    default: INFO

# 数据源配置
spring:
  datasource:
    dynamic:
      #设置默认的数据源
      primary: master
      datasource:
        master:
          username: root
          password: 12345
          url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          driverClassName: com.mysql.jdbc.Driver
        slave:
          username: root
          password: 12345
          url: jdbc:mysql://localhost:3306/slave?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          driverClassName: com.mysql.jdbc.Driver
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: study.domain.*
  global-config:
    # 数据库自增主键
    id-type: 0
    field-strategy: 2
    capital-mode: true
    refresh-mapper: true

#  #jta相关参数配置
  jta:
    #false:禁用JTA自动配置功能。可以使得本地事务也可以执行。true：彻底使用JTA环境，自动配置JMS，DataSource和JPA　beans将被升级以支持XA事务。
    enabled: true
    #日志地址，默认根目录下transaction-logs
    #log-dir: classpath:tx-logs
    #每个Atomikos的唯一ID,默认为ip地址
    #transaction-manager-id: txManager
  #autoconfigure:
    #exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
